### ISSUE TITLE
Package sometimes calls getName() on returnType not having that method

### ISSUE THREAD

**Issue by redalpha01** [scrumble-nl/laravel-model-ts-type#35] opened 2023-11-15 18:14 UTC
In one of my classes, I have a method like this 
```php
/**
* @param $size
* @return float|int
*/
private function sizeInKB($size): float|int
{
    return $size * 1000;
}
```

when running 
```
php artisan types:generate
```

it failed with 
```
Call to undefined method ReflectionUnionType::getName()
```

To avoid that issue, I temporarily surrounded the getName() in RelationPropertyGenerator -> getReturnType with 
```
if(method_exists($returnType, 'getName')) {
    return $returnType->getName();
}
```

**Comment by Luukdewaaier** [comment] 2023-12-22 22:09
Duplicate of #33

**Closed as completed by Luukdewaaier** 2023-12-22 22:09 UTC
